### ISSUE TITLE
Add notes scored field to auto page

### ISSUE THREAD

**Issue by atian7064** [FRC-1294/scouting-app#44]
Add fields that record the amount of notes scored in the speaker and the amp during auto.
The fields should have increment and deincrement buttons.

**Comment by ConfettiRaindrop** [comment]
Right now it's really hard to notice the input area for the notes scored, so either making it more obvious that the user has to type in there, or something better would be increment and decrement buttons since it can be hard to quickly type in a number, especially since auto can move really fast and that typed in numbers could have to change quickly

**Comment by loganRed9** [comment]
Fixed
